export const HOME_FETCH_CARD_BEGIN = 'HOME_FETCH_CARD_BEGIN';
export const HOME_FETCH_CARD_SUCCESS = 'HOME_FETCH_CARD_SUCCESS';
export const HOME_FETCH_CARD_FAILURE = 'HOME_FETCH_CARD_FAILURE';
export const HOME_FETCH_CARD_DISMISS_ERROR = 'HOME_FETCH_CARD_DISMISS_ERROR';
export const HOME_FLIP_CARD = 'HOME_FLIP_CARD';
export const HOME_NEXT_EXAMPLE = 'HOME_NEXT_EXAMPLE';
export const HOME_NEXT_MEANING = 'HOME_NEXT_MEANING';
